[project]
name = 'Blockchain-Based-Public-Health-Restaurant-Inspection-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certification-manager]
path = 'contracts/certification-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.health-alerts]
path = 'contracts/health-alerts.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
